[exporter]
query = [{ name = "list-posix-users" }, { name = "list-posix-groups" }]

   [exporter.scrape_flags]
   gids_info = true
   replication_status = true
   ldap_monitoring = true
   dsctl = true

[scrapers.dsctl]
instance = "default"
timeout_seconds = 10

[[scrapers.query]]
name = "list-posix-users"
filter = "(objectClass=posixAccount)"

[[scrapers.query]]
name = "list-posix-groups"
filter = "(objectClass=posixGroup)"
