[workspace]
resolver = "2"
members = [
   "config-389ds-rs",
   "exporter-389ds-rs",
   "haproxy-389ds-rs",
   "internal",
   "nagios-389ds-rs",
   "xtask",
]

   [workspace.dependencies]
   anyhow = "1.0.100"
   chrono = "0.4.43"
   clap = { version = "4.5.54", features = ["derive"] }
   ldap3 = "0.12.1"
   metrics = "0.24.3"
   metrics-exporter-prometheus = "0.18.1"
   openssl-sys = { version = "0.9.111", features = ["vendored"] }
   serde = { version = "1.0.228", features = ["derive"] }
   serde_json = "1.0.149"
   struct-field-names-as-array = "0.3.0"
   tokio = { version = "1.49.0", features = ["full"] }
   toml = { version = "0.9.11", features = ["preserve_order"] }
   tracing = "0.1.44"
   serde-aux = "4.7.0"
   tracing-subscriber = "0.3.22"
   sha2 = "0.10.9"
   tokio-util = { version = "0.7.18", features = ["rt", "tracing"] }
