[scrape_flags]
gids_info = true
replication_status = true
ldap_monitoring = true
dsctl = true

[dsctl]
instance = "default"

[[query]]
name = "list-posix-users"
filter = "(objectClass=posixAccount)"
timeout_seconds = 10

[[query]]
name = "list-posix-groups"
filter = "(objectClass=posixGroup)"
timeout_seconds = 10
