ldap_uri = "ldap://localhost"
page_size = 999

[exporter]
expose_port = 9100
expose_address = "127.0.0.1"
scrape_interval_seconds = 5
query = ["list-users"]

  [exporter.scrape_flags]
  gids_info = true
  replication_status = true
  ldap_monitoring = true
  dsctl = true


[haproxy]
expose_port = 9966
expose_address = "127.0.0.1"

  [haproxy.scrape_flags]
  replication_status = true
  ldap_monitoring = true

  [haproxy.scrape_interval_seconds]
  replication_status = 30
  ldap_monitoring = 5

  [[haproxy.query]]
  name = "list-users"
  action = "count-entries"
  greater_than = 0
  scrape_interval_seconds = 30

  [[haproxy.query]]
  name = "list-groups"
  action = "count-entries"
  greater_than = 0
  scrape_interval_seconds = 2

  [[haproxy.query]]
  name = "list-groups"
  action = "count-attrs"
  attr = "memberOf"
  greater_than = 0

[bind]
dn = "cn=Directory Manager"
# Try to decode it from base64 ;)
pass = "bm90IHNvIGVhc3kh"

[dsctl]
instance = "default"
timeout_seconds = 10

[[query]]
name = "list-users"
filter = "(&(objectClass=posixAccount)(objectClass=inetOrgPerson))"

[[query]]
name = "list-groups"
filter = "(&(objectClass=posixGroup)(objectClass=groupOfNames))"
attrs = ["memberof"]
