[toolchain]
components = [
   "rustfmt",
   "rust-analyzer",
   "rustc",
   "cargo",
   "rust-std",
   "clippy",
]
channel = "1.87.0"
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
