#!/bin/bash
DEFAULT_USER="haproxy-389ds-rs"
DEFAULT_GROUP="o11y-389ds-rs"

chown ${DEFAULT_USER}:${DEFAULT_GROUP} /etc/o11y-389ds-rs/haproxy.example.toml
chown root /etc/sudoers.d/haproxy-389ds-rs

systemctl daemon-reload
