[package]
name = "config-389ds-rs"
version = "0.3.0"
license = "MIT"
description = "Config package for 389ds exporter, haproxy and nagios"

   [package.metadata.generate-rpm]
   pre_uninstall_script = "config-389ds-rs/misc/rpm.preuninstall.sh"

      [[package.metadata.generate-rpm.assets]]
      dest = "/etc/o11y-389ds-rs/default.toml"
      mode = "640"
      source = "config-389ds-rs/misc/default.toml"
      user = "root"
      group = "o11y-389ds-rs"
      config = true
