[package]
name = "haproxy-389ds-rs"
description = "HAProxy agent for 389ds"
authors = ["Tomasz Durda<tomekdur@wp.pl>"]
version = "0.3.0-rc01"
edition = "2021"
license = "MIT"

   [package.metadata.deb]
   maintainer-scripts = "misc/deb.maintainer-scripts"

      [[package.metadata.deb.assets]]
      dest = "/etc/systemd/system/haproxy-389ds-rs.service"
      mode = "644"
      source = "misc/haproxy-389ds-rs.service"

      [[package.metadata.deb.assets]]
      dest = "/usr/bin/haproxy-389ds-rs"
      mode = "755"
      source = "target/release/haproxy-389ds-rs"

      [[package.metadata.deb.assets]]
      dest = "/etc/sudoers.d/haproxy-389ds-rs"
      mode = "440"
      source = "misc/haproxy.sudoers"

      [[package.metadata.deb.assets]]
      dest = "/etc/o11y-389ds-rs/haproxy.example.toml"
      mode = "600"
      source = "misc/haproxy-389ds-rs.minimal.toml"

   [package.metadata.generate-rpm]
   pre_install_script = "haproxy-389ds-rs/misc/rpm.preinstall.sh"
   post_install_script = "haproxy-389ds-rs/misc/rpm.postinstall.sh"
   pre_uninstall_script = "haproxy-389ds-rs/misc/rpm.preuninstall.sh"
   post_uninstall_script = "haproxy-389ds-rs/misc/rpm.postuninstall.sh"

      [[package.metadata.generate-rpm.assets]]
      dest = "/etc/systemd/system/haproxy-389ds-rs.service"
      mode = "644"
      source = "haproxy-389ds-rs/misc/haproxy-389ds-rs.service"
      config = true

      [[package.metadata.generate-rpm.assets]]
      dest = "/usr/bin/haproxy-389ds-rs"
      mode = "755"
      source = "target/x86_64-unknown-linux-musl/release/haproxy-389ds-rs"

      [[package.metadata.generate-rpm.assets]]
      dest = "/etc/sudoers.d/haproxy-389ds-rs"
      mode = "440"
      source = "haproxy-389ds-rs/misc/haproxy.sudoers"
      user = "root"

      [[package.metadata.generate-rpm.assets]]
      dest = "/etc/o11y-389ds-rs/haproxy.example.toml"
      mode = "600"
      source = "haproxy-389ds-rs/misc/haproxy-389ds-rs.minimal.toml"
      user = "exporter-389ds-rs"
      config = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
internal = { path = "../internal" }
tokio-util = { workspace = true }
actix-web = "4.12.1"
utoipa = { version = "5.4.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
utoipa-actix-web = "0.1.2"
