{
 "title": "389ds Exporter",
 "tags": [
  "ldap",
  "389ds",
  "bem2",
  "auth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({instance=~\"389ds.*\"},instance)"
    }
   },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter runtime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internal_runtime_seconds_active{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "389ds version",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "group by(instance, version) (monitor_version{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "dsctl_healthcheck_healthy{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthcheck errors",
   "type": "table",
   "description": "https://www.port389.org/docs/389ds/design/healthcheck-design.html",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "sum by(dsle, instance, severity) (dsctl_healthcheck_error{instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unresolvable primary GIDs",
   "type": "piechart",
   "description": "Users affected by unresolvable gids",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(gid) (query_gids_unresolvable_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Disk available",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monitor_disk_available{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk used (dirsrv, by host)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (monitor_disk_used{instance=~\"$instance\", partition=\"/var/lib/dirsrv\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk (use %)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "monitor_disk_use_percentage{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Agreements",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "group by(host, agreement, instance) (replication_agreement{instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active agreements by host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (replication_agreement{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max retrun code for agreement (by host)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 26 },
   "targets": [
    {
     "expr": "max by(instance) (replication_agreement_ldap_status{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Posix groups count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(custom_query_object_count{instance=~\"$instance\", query=\"list-posix-groups\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Posix users count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg(custom_query_object_count{instance=~\"$instance\", query=\"list-posix-groups\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difference from average object count (groups)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(custom_query_object_count{instance=~\"$instance\", query=\"list-posix-groups\"} - avg(custom_query_object_count{instance=~\"389ds.*\", query=\"list-posix-groups\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difference from average object count (users)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(custom_query_object_count{instance=~\"$instance\", query=\"list-posix-users\"} - avg(custom_query_object_count{instance=~\"389ds.*\", query=\"list-posix-users\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAPs response time (groups)",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "custom_query_duration_ms{instance=~\"$instance\", query=\"list-posix-groups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAPs response time (users)",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "custom_query_duration_ms{instance=~\"$instance\", query=\"list-posix-users\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Connections by IP",
   "type": "piechart",
   "description": "Avg connections by ip (since exporter startup)\n",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ip) (monitor_connection_avg_by_ip{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections (counted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 57 },
   "targets": [
    {
     "expr": "monitor_connection_count{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections by DN",
   "type": "piechart",
   "description": "Avg connections by dn (since exporter startup)",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dn) (monitor_connection_avg_by_dn{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Average connections (last 1h)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(monitor_connection_count{instance=~\"$instance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Average connections (interval)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(monitor_connection_count{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total connections since last restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "monitor_totalconnections{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit max thread",
   "type": "bargauge",
   "description": "Displays how many times a connection [hit max thread](https://docs.redhat.com/en/documentation/red_hat_directory_server/11/html/performance_tuning_guide/tracking-performance#monitoring-directory-server-using-the-command-line)",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_maxthreadsperconnhits{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections (SNMP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "monitor_snmp_connections{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}