{
 "title": "389ds healthchceck errors",
 "tags": [
  "389ds",
  "auth",
  "bem2",
  "ldap"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "ldap_uri", "label": "LDAP URI (exported instance)", "query": { "query": "label_values(ldap_uri)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({ldap_uri=~\".+\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors by instances and type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dsctl_healthcheck_error{ldap_uri=~\"$ldap_uri\", instance=~\"$instance\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (dsctl_healthcheck_error{ldap_uri=~\"$ldap_uri\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by  type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(dsle) (dsctl_healthcheck_error{ldap_uri=~\"$ldap_uri\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by ldap_uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(ldap_uri) (dsctl_healthcheck_error{ldap_uri=~\"$ldap_uri\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by  severity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(severity) (dsctl_healthcheck_error{ldap_uri=~\"$ldap_uri\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by  severity and instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(severity, instance) (dsctl_healthcheck_error{ldap_uri=~\"$ldap_uri\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}